-- Studii Phase 2 schema migration for Supabase.
-- Replaces Firestore users stats + wrapped summaries storage with Postgres tables.

create extension if not exists pg_cron;

create table if not exists public.users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stats jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.wrapped_summaries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  period_id text not null,
  personality text not null,
  top_buddy text,
  top_buddy_overlap_hours double precision not null default 0,
  power_hour integer not null default 0,
  power_day integer not null default 0,
  longest_session_min integer not null default 0,
  most_pomodoros_day integer not null default 0,
  streak integer not null default 0,
  total_hours double precision not null default 0,
  share_card_url text,
  generated_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint wrapped_summaries_user_period_unique unique (user_id, period_id)
);

create index if not exists idx_wrapped_summaries_user_id on public.wrapped_summaries (user_id);
create index if not exists idx_wrapped_summaries_period_id on public.wrapped_summaries (period_id);

alter table public.users enable row level security;
alter table public.wrapped_summaries enable row level security;

drop policy if exists "users_select_own" on public.users;
create policy "users_select_own"
on public.users
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users_insert_own" on public.users;
create policy "users_insert_own"
on public.users
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users_update_own" on public.users;
create policy "users_update_own"
on public.users
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users_delete_own" on public.users;
create policy "users_delete_own"
on public.users
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "wrapped_summaries_select_own" on public.wrapped_summaries;
create policy "wrapped_summaries_select_own"
on public.wrapped_summaries
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "wrapped_summaries_insert_own" on public.wrapped_summaries;
create policy "wrapped_summaries_insert_own"
on public.wrapped_summaries
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "wrapped_summaries_update_own" on public.wrapped_summaries;
create policy "wrapped_summaries_update_own"
on public.wrapped_summaries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "wrapped_summaries_delete_own" on public.wrapped_summaries;
create policy "wrapped_summaries_delete_own"
on public.wrapped_summaries
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at_timestamp();

drop trigger if exists wrapped_summaries_set_updated_at on public.wrapped_summaries;
create trigger wrapped_summaries_set_updated_at
before update on public.wrapped_summaries
for each row
execute function public.set_updated_at_timestamp();
